# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true

# Project properties
group=dev.lambdaurora
java_version=21

# Mod Properties
mod_version=2.0.0
mod_name=Aurora's Lanterns
mod_namespace=auroraslanterns
modrinth_id=xABbFTq3
curseforge_id=1368734

fabric.loom.dropNonIntermediateRootMethods=true
