# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Project properties
group=dev.lambdaurora
java_version=21

# Mod Properties
mod_version=1.1.5
mod_name=Aurora's Lanterns
mod_namespace=auroraslanterns
modrinth_id=xABbFTq3
curseforge_id=

fabric.loom.dropNonIntermediateRootMethods=true
